FoohartUserBundle:
    resource: "@FoohartUserBundle/Resources/config/routing.yml"
    prefix:   /

FoohartBlogBundle:
    resource: "@FoohartBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
