security:
    encoders:
        Foohart\UserBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        administrators:
            entity: { class: FoohartUserBundle:User, property: username }

    firewalls:
        admin_area:
            pattern:    ^/blog
            http_basic: ~

    access_control:
        - { path: ^/blog, roles: ROLE_ADMIN }