parameters:
#    foohart_user.example.class: Foohart\UserBundle\Example

services:
#    foohart_user.example:
#        class: %foohart_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
